/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo01AccessJavaField */

#ifndef _Included_Demo01AccessJavaField
#define _Included_Demo01AccessJavaField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo01AccessJavaField
 * Method:    changeJavaField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Demo01AccessJavaField_changeJavaField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_Demo01AccessJavaField_changeJavaStaticField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_Demo01AccessJavaField_callJavaMethod
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_Demo01AccessJavaField_callJavaStaticMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
